---
title: "crash dynamic"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library, include=FALSE}
library(igraph)
library(ggnetwork)
library(tidyr)
library(tibble)
library(gplots)
library(dendextend)
library(tidyverse)
library(RColorBrewer)
```


```{r data, include=FALSE}

load("/home/bahar/Desktop/project/networkS-P500/data/daily_cosinus_2018.rda")
head(daily_res[1])

```


## 3 day before crash

day "2018-12-19"

```{r 19, echo=FALSE}
B4crash <- daily_res[["2018-12-19"]]
B4crash_sample <- spread(B4crash[,-1], Ticker2, cos_vecs)
B4crash_sample <- column_to_rownames(B4crash_sample, var = "Ticker")
B4crash_sample[is.na(B4crash_sample)] <- 0
B4crash_sample <- B4crash_sample + t(B4crash_sample)
B4crash_sample <- as.matrix(B4crash_sample)

# plot dendo --------------------------------------------------------------

normal.dist <- as.dist(B4crash_sample)
normal.tree <- hclust(normal.dist, method="complete")
normal.dend <- as.dendrogram(normal.tree) # create dendrogram object
plot(color_branches(normal.dend, h=1),leaflab="none")
```

## 2 day before crash

day "2018-12-20"

```{r 20, echo=FALSE}
B4crash <- daily_res[["2018-12-20"]]
B4crash_sample <- spread(B4crash[,-1], Ticker2, cos_vecs)
B4crash_sample <- column_to_rownames(B4crash_sample, var = "Ticker")
B4crash_sample[is.na(B4crash_sample)] <- 0
B4crash_sample <- B4crash_sample + t(B4crash_sample)
B4crash_sample <- as.matrix(B4crash_sample)

# plot dendo --------------------------------------------------------------

normal.dist <- as.dist(B4crash_sample)
normal.tree <- hclust(normal.dist, method="complete")
normal.dend <- as.dendrogram(normal.tree) # create dendrogram object
plot(color_branches(normal.dend, h=1),leaflab="none")
```

## a day before crash

day "2018-12-21"

```{r 21, echo=FALSE}
B4crash <- daily_res[["2018-12-21"]]
B4crash_sample <- spread(B4crash[,-1], Ticker2, cos_vecs)
B4crash_sample <- column_to_rownames(B4crash_sample, var = "Ticker")
B4crash_sample[is.na(B4crash_sample)] <- 0
B4crash_sample <- B4crash_sample + t(B4crash_sample)
B4crash_sample <- as.matrix(B4crash_sample)

# plot dendo --------------------------------------------------------------

normal.dist <- as.dist(B4crash_sample)
normal.tree <- hclust(normal.dist, method="complete")
normal.dend <- as.dendrogram(normal.tree) # create dendrogram object
plot(color_branches(normal.dend, h=1),leaflab="none")
```

## crash day

day "2018-12-24"

```{r 24, echo=FALSE}
B4crash <- daily_res[["2018-12-24"]]
B4crash_sample <- spread(B4crash[,-1], Ticker2, cos_vecs)
B4crash_sample <- column_to_rownames(B4crash_sample, var = "Ticker")
B4crash_sample[is.na(B4crash_sample)] <- 0
B4crash_sample <- B4crash_sample + t(B4crash_sample)
B4crash_sample <- as.matrix(B4crash_sample)

# plot dendo --------------------------------------------------------------

normal.dist <- as.dist(B4crash_sample)
normal.tree <- hclust(normal.dist, method="complete")
normal.dend <- as.dendrogram(normal.tree) # create dendrogram object
plot(color_branches(normal.dend, h=1),leaflab="none")
```